language: node_js
node_js:
 - "node"
env:
  global:
    - MONGO_URI_LOCAL=mongodb://127.0.0.1/stub
    - SECRET=thisismyappsecret
    - DEBUG=true
    - TEST=true
    - LOCAL=true
    - DB_USERNAME=root
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_PASSWORD=''
    - DB_DATABASE=stub
services:
  - mongodb
  - mysql
before_script:
  - tsc
before_install:
   - mysql -e 'CREATE DATABASE IF NOT EXISTS stub;'
