version: '2'
services:
  web:
      build: .
      ports:
      - 3000:80
      volumes:
      - "./web:/app/web"
      - "./app.ts:/app/app.ts"
      - "./.env:/app/.env"
      - "./dist:/app/dist"
      - "./test:/app/test"
      depends_on:
        - mongo
      links:
        - mongo
      environment:
         MONGO_URI: ${MONGO_URI}
         DEBUG: ${DEBUG}
         SECRET: ${SECRET}
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo:
